pipeline {
    agent any
    
    environment {
        // [수정!] ECR 콘솔 우측 상단 12자리 숫자 직접 입력
        AWS_ACCOUNT_ID = '877009927021' 
        AWS_REGION     = 'ap-northeast-2' 
        // [수정!] 리포지토리 이름 직접 입력
        ECR_REPO_NAME  = 'al7/ci-jenkins'
        ECR_REGISTRY   = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        TAG            = "v${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                // SCM 설정(Git)에서 가져온 코드를 사용합니다
                checkout scm 
            }
        }

        stage('AWS ECR Login') {
            steps {
                // [체크!] 젠킨스에 등록한 AWS 키 ID와 일치해야 함
                withAWS(credentials: 'aws-ecr-credentials', region: "${AWS_REGION}") {
                    sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}"
                }
            }
        }

        stage('Build and Push') {
            steps {
                // aL7ive 폴더로 이동해서 Dockerfile을 찾습니다
                dir('aL7ive') { 
                    bat "docker build -t ${ECR_REGISTRY}/${ECR_REPO_NAME}:${TAG} ."
                    bat "docker tag ${ECR_REGISTRY}/${ECR_REPO_NAME}:${TAG} ${ECR_REGISTRY}/${ECR_REPO_NAME}:latest"
                    bat "docker push ${ECR_REGISTRY}/${ECR_REPO_NAME}:${TAG}"
                    bat "docker push ${ECR_REGISTRY}/${ECR_REPO_NAME}:latest"
                }
            }
        }
    }
}