pipeline {
    agent any
    
    environment {
        AWS_ACCOUNT_ID = credentials('AWS_ACCOUNT_ID')
        AWS_REGION     = 'ap-northeast-2' 
        ECR_REGISTRY   = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        IMAGE_NAME     = "${env.ECR_REPO_NAME}"
        TAG            = "v${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('AWS ECR Login') {
            steps {
                withAWS(credentials: 'aws-credentials-id', region: "${AWS_REGION}") {
                    sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}"
                }
            }
        }

        stage('Build and Push') {
            steps {
                // aL7ive 폴더로 이동해서 빌드 후 ECR로 바로 푸시
                dir('aL7ive') { 
                    sh "docker build -t ${ECR_REGISTRY}/${IMAGE_NAME}:${TAG} ."
                    sh "docker tag ${ECR_REGISTRY}/${IMAGE_NAME}:${TAG} ${ECR_REGISTRY}/${IMAGE_NAME}:latest"
                    sh "docker push ${ECR_REGISTRY}/${IMAGE_NAME}:${TAG}"
                    sh "docker push ${ECR_REGISTRY}/${IMAGE_NAME}:latest"
                }
            }
        }
    }
}
